
package br.com.correios.service.atende.cliente;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-02-22T14:27:41.733-03:00
 * Generated source version: 3.3.0
 */

@WebFault(name = "Exception", targetNamespace = "http://cliente.bean.master.sigep.bsb.correios.com.br/")
public class Exception_Exception extends java.lang.Exception {

    private br.com.correios.service.atende.cliente.Exception exception;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, br.com.correios.service.atende.cliente.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, br.com.correios.service.atende.cliente.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public br.com.correios.service.atende.cliente.Exception getFaultInfo() {
        return this.exception;
    }
}
